### ISSUE TITLE
motor configuration and wiring

### ISSUE THREAD

**Issue by physics2000** [PepeTheFroggie/EspCopter#2]
from image you use quad x type.
motors 1 and 2 ccw,
motors 3 and 4 cw.
but in PWMOUT which motor connected to which esp8266 pin?
does it motor1(ccw) to pin14 and motor2(ccw) pin12
or motor1(ccw) to pin14 and motor3(cw) pin12 ?

**Comment by AbuHelal** [comment]
how i can operate the drone thanks
